### ISSUE TITLE
Unreasonably long preparation time?

### ISSUE THREAD

**Issue by hoverkraft** [alessandro-zomparelli/tissue#102]
Hi Alessandro, I am following your reaction-diffusion video here: https://www.youtube.com/watch?v=J-0NzU1TmIY&t=14s and see you have really low preparation time.

My numbers look like this, which is magnitudes higher for preparation time:
![image](https://user-images.githubusercontent.com/461848/112309327-81ca2a80-8ca3-11eb-8251-e3958543ea7e.png)

I am using the same object you are (icosphere lvl6, ~10k verts), CPU is a 3950x, Windows 10, Tissue is version 3.50 b-290 dev. I've tried Blender 2.92 and 2.93 alpha.  Numba is installed and seems to be working.

What are the factors for prep time? Anything I can do about it?
Thanks, and thank you for developing Tissue!

**Comment by alessandro-zomparelli** [comment]
Hi @hoverkraft perfect timing for this message, because I just implemented a Fast Bake method that just skips the preparation time :-) https://twitter.com/alessandrozompa/status/1374498753353187332

Unfortunately, this works only for baking and it doesn't update the vertex groups according to some modifiers, in case you have some dynamic interaction through them. If you just want to see how your pattern growth without real interactions with the scene, then you should definitely use that option. It's on by default in the b290-dev branch. Let me know!

Regarding your question, in general, there is no much that you can do in order to improve the preparation time, this the time that is needed in order to load the information from the mesh and the vertex groups. Reading them is unfortunately still a bit slow with the blender API.

Alessandro

**Comment by hoverkraft** [comment]
That's great news! I will be using this functionality for sure. I was just wondering why there might be such a big difference between your and my system, 0.002 vs 0.2 ms. Is the data written to disk or only pushed into memory? I am asking bc I have my Blender related directories on a rather slow network drive, that might play a role.

**Comment by alessandro-zomparelli** [comment]
@hoverkraft basically what happens in the preparation time is that the mesh is loaded together with the vertex groups. And that's usually slow. I don't think that the drive has a big role here, I think it's something more related to the CPU.

**Comment by kendrick90** [comment]
I can definitely attest to a hard drive bottleneck I have blender installed on my HD instead of my SSD and it's maxed out while my CPU is chilling at 30%. 
![image](https://user-images.githubusercontent.com/50811104/123909942-9e26d480-d92e-11eb-8f98-2d383d6d6222.png)

**Comment by alessandro-zomparelli** [comment]
hi @kendrick90 I just realized that my previous answer wasn't correct. Yes, when you use the bake option, it uses data written on the disk. In theory, if you set the baking folder on the SSD it should be faster.
