### ISSUE TITLE
Patch mode subdivision levels 

### ISSUE THREAD

**Issue by Nicknroll** [alessandro-zomparelli/tissue#104]
Hi again!
I have small proposal to add a bit of non-destructivness to the Patch mode. 

Short description of a problem:
For now i have to copy base mesh each time for applying of necessary subdiv level for Patch tessellation.
![Screenshot_2](https://user-images.githubusercontent.com/74839903/112850092-5cc62500-90b2-11eb-88d1-d3ac3eeb67d4.jpg)

So here is proposal to add a parameter which allows to choose at which level of subdivision apply Patch mode:
![Screenshot_3](https://user-images.githubusercontent.com/74839903/112850394-a0b92a00-90b2-11eb-9096-412307d61a37.jpg)

I hope its okay that i asking about feature request :)

Best regards!
Nick

**Comment by alessandro-zomparelli** [comment]
Hi @Nicknroll thanks for your feedback. That's a nice idea, and any feedback is appreciated, especially constructive feedback like yours. 
I wonder though if such a setting would be intuitive with several modifiers on the object. This is what I usually do. I use two different subdivision surface modifiers. The first one control the number of components, the second one will be used for the smoothness of the patch. There is no need to apply the modifier because the patch works only on the last  Subdivision surface (or multi-resolution) of the modifier stack. This is actually nice because when you turn on the wireframe visualization in the overlays you will see the correct number of patches. I have the feeling that controlling that from the modifiers stack is simpler and may be less confusing. What do you think?

**Comment by Nicknroll** [comment]
Ohh i didn't notice it works only with last subdiv modifier in a stack. 
This is exactly what i looking for.
Thank you!
