### ISSUE TITLE
Tessellate lock direction

### ISSUE THREAD

**Issue by Nicknroll** [alessandro-zomparelli/tissue#105]
One more proposal. 
Perhaps it is already implemented but i can't find a way to do this. 
I tried to use custom normals but seems they ignored by algorithm.

For instance i have a tower with transition from arched window panels at bottom to rectangular at the top. 
So I'd wish my panels did not have z-axis distortion, is this possible to add in future?

![Screenshot_6](https://user-images.githubusercontent.com/74839903/112966115-96e70380-9152-11eb-8260-6987d1640df5.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/74839903/112966127-99e1f400-9152-11eb-9474-e598b33dfb7c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/74839903/112968778-49b86100-9155-11eb-8f8f-6d23ce279e98.jpg)

In GH i can just offset my panels and create custom morph boxes, so it would be nice to control panels direction in Tissue.
I guess this would be widely used for architectural purposes. 

Also, may be it have some sense to add support for custom normals? For now its not very handy to control them but with upcoming Spreadsheets editor i hope things may change.

Best wishes!
Nick

**Comment by alessandro-zomparelli** [comment]
hi @Nicknroll yes you can. You can use Direction Object, and make a second object that is offset in XY but not in Z. Your boxes will be created in between the two geometries. Let me know if it works fine.
The directional control of the tessellation is indeed an interesting topic. I will consider this your suggestion, maybe in combination with vertex groups. A common issue that I have sometimes, is that I want to make sure that the components on the ground have normals parallel to the ground in the base of my structure. Like in this example: https://www.instagram.com/p/CCVme4fJV_3/
I have two options for that: 
- mirroring the structure vertically in order to have the normals aligned to the ground
- using a second object
Having a simple setting for that would definitely help. Thanks for your suggestion.

**Comment by Nicknroll** [comment]
@alessandro-zomparelli Thx, Direction Object works well, and resolve problem of distorted eges! 
![Screenshot_5](https://user-images.githubusercontent.com/74839903/112994547-0a990880-9173-11eb-9b2f-5168b3811fb5.jpg)

But there still a problem to get this object, because there is no easy way to offset mesh without z distortion. 

Extrude along normal unfortunately can't be locked in xy-plane:
![Screenshot_3](https://user-images.githubusercontent.com/74839903/112993592-09b3a700-9172-11eb-8f8f-6fafd03de3fe.jpg)

The only way is scale my shape in xy-plane and then manually align perpendicular to base surface each vertex. Also scaling  approach is only suitable for rectangular shapes:
![Screenshot_4](https://user-images.githubusercontent.com/74839903/112993998-77f86980-9172-11eb-8523-8defce4d4efb.jpg)

So, extrude faces along normals locked in xy plane could be an option.

**Comment by Nicknroll** [comment]
Found a way to avoid vertical distortion using curve offset tool.
