### ISSUE TITLE
Tissue tab not appearing after installing and activating tissue

### ISSUE THREAD

**Issue by kellyegan** [alessandro-zomparelli/tissue#11]
Using Blender 2.78 on a Mac after activating the plugin the tissue tools appear in the tools tab but there is no tissue tab for tesselate.

**Comment by enzyme69** [comment]
I was going to report the same thing :\ something is not right.

**Comment by enzyme69** [comment]
Explanation by Alex:

Alessandro Zomparelli Yes, I changed the UI according to some requests in order to make the add-on embedded in the next version of blender. You should have a panel in Tools and another panel in Create.
![screen shot 2017-06-20 at 17 31 35](https://user-images.githubusercontent.com/3952687/27321671-6beba3ec-55de-11e7-9206-1741d2cfb08f.png)

**Comment by kellyegan** [comment]
Ahh there it is. Great.
