### ISSUE TITLE
when tesselateing and changing face direction it overlaps with the old and the old will not refresh

### ISSUE THREAD

**Issue by Totoro51212** [alessandro-zomparelli/tissue#124]
![image](https://user-images.githubusercontent.com/87871970/127903868-2e8e9227-2ba0-4f15-b7d9-ed79d0f337d4.png)

**Comment by alessandro-zomparelli** [comment]
@Totoro51212 this answer arrives quite late, sorry for that. I was running through old unresolved issues and I just saw this one. The solution is using Local or Global coordinates for the component. Otherwise, the bounding box of the component will be deformed in order to match the target face. This does not allow any type of overlap. You may have the same issue when you try to have gaps between the components.
This video may help: https://www.youtube.com/watch?v=PRIcB1Q-gK4
