### ISSUE TITLE
Blender 2.93 Reaction diffusion simulation doesn't stop

### ISSUE THREAD

**Issue by facuhead** [alessandro-zomparelli/tissue#126]
Hello!

Im actually embarrased, because i cant preserve the simulation itself. When i come back to the begining of the timeline the simulation continues reproducing. Do you have some way to make a bake of the animation or something like this ?

**Comment by alessandro-zomparelli** [comment]
hi @facuhead, sorry, this reply arrives really late... With the Reaction-Diffusion you can use the Bake option: 
![image](https://user-images.githubusercontent.com/6708848/156893213-eae77e92-e54b-4571-9a9b-e806abd59f5f.png)
Before using that, you need to either save your blender file (in order to use its file path for the cache) or define the cache folder manually.
