### ISSUE TITLE
Cross Contour Curve Direction

### ISSUE THREAD

**Issue by Myrkskog** [alessandro-zomparelli/tissue#153]
First and foremost, thank you for these tools!
Any chance the curves can be created facing the same direction?
I am using a profile that has an origin that is not centered.
This is to mimic the extrusion deposition I get when using IceSL slicer with the post-process perimeter plugin.
The IceSL post process tends to push the deposition beyond the boundary of my 3d model. This is fine, as I just have to design around this.

Tissue will allow me to visualize this more easily when I iterate on the design. This will be tremendously helpful to get a ballpark idea of how my parts will mate.

This is more a quality of life request. Switching the direction of each curve is easy enough to handle yet tedious. It would be fantastic to refresh the cross contour object keeping the curve direction.

Also, I cannot seem to get the first curve to appear at the base of my model. The objects origin is at the bottom and positioned at the world origin. Any idea what I am doing incorrectly?
 
![Screenshot from 2023-10-11 12-52-13](https://github.com/alessandro-zomparelli/tissue/assets/69390185/b9e8ba64-26ae-4163-91ae-c7945ef0e346)

My first attempt at this workflow was using https://github.com/Heinz-Loepmeier/nozzleboss

The design iterations had to be fed to the slicer each time and imported into Blender over and over. I would then scale the imported gcode; modify the mesh object to remove the layer height (as I just needed the path); Convert to curve, and then apply the profile I wanted. This gave me a good representation, but not a very fluid experience. Tissue on the other hand I think will make this process quick.

**Comment by alessandro-zomparelli** [comment]
Hi @Myrkskog thanks for your message and for explaining your workflow, it really helps me understand how the tool is used :-)
Regarding your request, I guess it is possible and I understand it would make your life easier in this case. I will consider that in the future, but I have to say that there are other priorities in the development at the moment.
Here is a solution though, you can use the Displace Pattern option. Your mesh object should have a completely red vertex group, and use the settings (green) from the image:
![image](https://github.com/alessandro-zomparelli/tissue/assets/6708848/37d0910c-fad5-4c6e-8a0c-ed0195488236)
For the first layer missing, this is actually something that is happening for a reason, because the contour is always computed from below. Since there are no faces below the height 0, this specific layer is missing. One hack would be to just give a tiny translation to the curves using the Offset Values parameter while using the **Vector** Mode (red in the image).
Let me know if this helps!
ciao
Alessandro

**Comment by Myrkskog** [comment]
@alessandro-zomparelli Thank you for taking the time to help. I will try this out tomorrow. I take it the origin should remain centered on the profile shape. Thank you for the future consideration and keep plugging away at your priorities! I am uncertain if this is the place to share results. I would like to show some process in context for you.
