### ISSUE TITLE
Installed 3.14 but not showing up in addons

### ISSUE THREAD

**Issue by JoelGodin** [alessandro-zomparelli/tissue#24]
It installed in the folder, but can't find it in addons.  
Removed 3.5 one, installed this one, but not there.

Tried 2 other addons, and they install and show okay.

**Comment by alessandro-zomparelli** [comment]
Thanks @JoelGodin  , it has always been a problem. I thinks it is because of the . in the folder name. If you remove them it should work. I'll do something about that...

I suggest you to check this branch, that is the development branch for Blender 2.80: https://github.com/alessandro-zomparelli/tissue/tree/b280-dev 
Always the most updated

**Comment by JoelGodin** [comment]
Okay, that worked.
Thanks
