### ISSUE TITLE
Tessellate crashes in blender 2.8 beta with tissue b2.80-dev

### ISSUE THREAD

**Issue by KaiSteinert** [alessandro-zomparelli/tissue#35]
Hi I get the following stack

Read prefs: /home/kai/.config/blender/2.80/config/userpref.blend
found bundled python: /home/kai/Apps/blender/2.80/python
Traceback (most recent call last):
  File "/home/kai/.config/blender/2.80/scripts/addons/tissue-b280-dev/tessellate_numpy.py", line 2378, in execute
    auto_layer_collection()
  File "/home/kai/.config/blender/2.80/scripts/addons/tissue-b280-dev/tessellate_numpy.py", line 67, in auto_layer_collection
    if layer.hide_viewport or layer.collection.hide_viewport:
AttributeError: 'LayerCollection' object has no attribute 'hide_viewport'

location: <unknown location>:-1

location: <unknown location>:-1

If I delete 'layer.hide_viewport or ' in line 67 in tessellate_numpy.py it works. I don't now the side effect though.

**Comment by alessandro-zomparelli** [comment]
Hi Kai,
thanks for reporting. I just tested it on my Blender and it seems working fine. Are you using the latest Blender build?

Btw, I created that function, because if your active collection is hidden, the generated object will be placed automatically in that collection, and it will give an error for the following operations in the Tissue code.

**Comment by KaiSteinert** [comment]
Hi Alessandro,
I was running a version from 12. 2018. With the current build it works.
Thank you for your time and this great addon!
