### ISSUE TITLE
Help with pieces turning...

### ISSUE THREAD

**Issue by Bennewith** [alessandro-zomparelli/tissue#36]
This is not really a bug issue so I'm not sure if it's ok to ask about this here. 
I'm using Tessalate. I've created a component mesh similar to one you used in one of your videos. My base mesh is a logo that I drew and then modeled. When I tessalate the component to the base mesh, some pieces end up turning in different directions. Is there any advice you can give on how to correct this? 
![Screen Shot 2019-05-03 at 4 14 48 PM](https://user-images.githubusercontent.com/233897/57170148-b2f39600-6dbf-11e9-8a2f-37bfc7df137a.png)
I've attached a screen shot. I hope this helps.
Thanks for a great add-on!

**Comment by alessandro-zomparelli** [comment]
Hi @Bennewith 
the orientation of the components depends on how the vertices for each face. This is not something that you can really control usually. For that reason you can select some faces in your source base mesh, and use [Rotate Faces](https://github.com/alessandro-zomparelli/tissue/wiki/Tissue-Tools#rotate-faces). It will change the indexes and will refresh the Tessellations that depends on that base mesh.

As an alternative, if you are familiar with UV mapping, you can unwrap your geometry, making sure that the rotation of your base mesh in the UV layout is almost consistent. Then in the Tessellation you can use [Active UV](https://github.com/alessandro-zomparelli/tissue/wiki/Tessellate#active-uv) in order to align the components accordingly. This method works better with comple geometries, but with a good topology.
