### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by Scribblerrrr** [alessandro-zomparelli/tissue#40]
I'm continuously getting an error saying "name'module_filesystem_remove' is not defined"
please help me with this

**Comment by alessandro-zomparelli** [comment]
Hi, can you please give more information in order to spot the reason of your issue?
What's the blender and tissue version?
When does the error occurs? What are you trying to do?
Please, open the console window where you should see more information about the error and copy and paste everything here.

Alessandro

**Comment by alessandro-zomparelli** [comment]
@Scribblerrrr I'm closing that issue. Let me know if you still need a solution for that.

**Comment by Scribblerrrr** [comment]
Hi Alessandro
Sorry for the late reply
The issue is I couldn't install tissue. And I'm using blender2.8

Thanks for your response.
