### ISSUE TITLE
Change the name of Tessallate Button

### ISSUE THREAD

**Issue by kosirm** [alessandro-zomparelli/tissue#60]
Hi, first of all huge thank you for this amazing plugin, I'm having a lot of fun with it.
I would like to suggest some small UI change, which would help first time users and add to UI consistency, I think. Tessallate button actually opens tessallation properties popup window. From the first time user perspective it is like: "Ok, if I click this button, it will tessallate, but where can I set tessallation properties first?"
Common practice is that buttons have names of what they do if it is possible.
I would suggest that you change the name of the button to Tessellation Settings or something like this, which would make UI more self-explanatory. And then on the popup, on the end it is OK button. OK what? OK to save settings somewhere, or OK to tessalate? I would change OK button name to "Tessallate" or "OK, Tessalate" or "Tessalate Now" or something like this.
 
Beside these small and minor UI inconsistencies, for me this is one of the most genious blender plugins. Congrats!

**Comment by alessandro-zomparelli** [comment]
Hi @kosirm thank you for your feedback, I really appreciate your help!
I read your suggestion, but to be honest, I can't really see the problem. I think that this is quite consistent with Blender's UI, indeed, I am using the options provided by Blender's API and suggested by the developers. Let me be more specific.
Initially pressing Tessellate it just did the tessellation showing after that the settings in the operator panel (like any operator in Blender). 
Then, the developers suggested to use the operator's pop-up option that allows to chose the settings **before** pressing **OK** for executing the Tessellation. The idea was to waste less time with complex tessellations, but also showing the number of generated polygons before (this usefull option is not there anymore, because now with iterations and multicomponent it became a bit more tricky/heavy).
The **OK** button is a default button, I'm not sure if I can easily change it. I think that changing that would involve to rewrite the nature of the operator (I just did some quick research, and an approach would be to create an operator for the dialogue box, wiith inside other operators, like "Tessellate Now": https://blender.stackexchange.com/questions/82317/how-to-trigger-menus-from-operators-in-python)
At this point my though is: if the idea is to improve the consistency with the Blender's UI, is it not better to keep the behaviour of the dialogue box as it is by default? 

For a more complete discussion, I would also like to introduce another topic, that maybe can help figuring out what would be the best solution. I was thinking that the Tessellation have now a lot of settings, with some specific combinations you can drastically change the way to use it: branching systems, multicomponents, wireframe. I like the idea that all the settings can be combined in order to give more freedom, but I'm also considering to provide some presets for them. In that case, which options should I provide? Whould that create confusion due to the higher amount of buttons in the Tissue Panel?

**Comment by kosirm** [comment]
Man, I'm so sorry for taking your precious time with my remarks, thanks for reply... Regarding grow of your plugin I would concider to talk/contact with teams for parametric design (Sverchok, Animation Nodes, Sorcar), they already have all infrastructure for working with nodes, which I think would be more appropriate for your plugin if it is really going to grow... Maybe you can introduce your plugin as special Tessalation section of Animation nodes... I don't even know it is possible, since they use cyton and you are using numba... Just my 0.2 $

**Comment by kosirm** [comment]
I just notices, that Jimmy Gunawan (aka blendersushi, guy with 1000+ Sverchok videos) [promoted your plugin](https://youtu.be/QRS8mzRUMHs) and experimented to do something similar with Sverchok back in 2017. But that you probably know already :) Just wanted to direct your attention to node based Blender tools, because I think that for your plugin would be great if it would be part of bigger parametric design ecosystem, like Animation nodes or Sverchok... because it could profit from various other nodes which are already available there...
