### ISSUE TITLE
Question: Is it possible to use vertex groups for controlling component thickness / scaling?

### ISSUE THREAD

**Issue by Taroslord** [alessandro-zomparelli/tissue#62]
Hi.

I would like to know if there is a way to control the component thickness by using vertex group values (weights).
Vertex value 1 = 100 % scaling
Vertex value 0.5 = 50 % scaling
Vertex value 0 = 0 % scaling

Or is there another way for a dynamic thickness?

Thank you!

**Comment by Taroslord** [comment]
Never mind. I've found it... Just move to Blenders weight mode. :)

**Comment by alessandro-zomparelli** [comment]
Hi! Yes is possible, but using the shapekeys.
It's a bit more complex, but also more flexible. I thought about introducing a specific setting for that, but it doesn't have an high priority because there is currently a turnaround. If you need some info on how to use the shapekeys you can check this video:
https://www.youtube.com/watch?v=2Wcu9E0EGEM

There is another way, undocumented for the moment. Direction: "Custom". It moves the direction of the tessellation (not only the thickness) according to the shape keys of the base mesh.

This is the basis:
![immagine](https://user-images.githubusercontent.com/6708848/76202083-96509780-61f4-11ea-8fdb-18a9fd8c2f0d.png)
This is key 1:
![immagine](https://user-images.githubusercontent.com/6708848/76202143-ab2d2b00-61f4-11ea-8f0f-b54a675ef260.png)

This is the Tessellation:
![immagine](https://user-images.githubusercontent.com/6708848/76202296-e4659b00-61f4-11ea-9bc0-64c8ad8e29e6.png)

Important: set the Key 1 value to 1, and use Constant thickness.

**Comment by alessandro-zomparelli** [comment]
@Taroslord now it's possible directly from the Tessellation settings
