### ISSUE TITLE
Button 'Dual Mesh' doesn't work on Blender 2.81.16

### ISSUE THREAD

**Issue by matfoss1** [alessandro-zomparelli/tissue#65]
Hi Alessandro, I'm trying to make a dual mesh out of a basic sculpted mesh, just as in this tutorial:

https://www.youtube.com/watch?v=Zo2phSY4hrE

at minute 4:10

but somehow it doesn't work and the console gives me this error:

KeyError: 'bpy_prop_collection[key]: key "DualMesh_QUAD_Component" not found'

Do you know by chance the reason why?

Thanks a lot

Matteo

<img src="https://i.ibb.co/v1QcBmC/dualmesh-error.jpg">

**Comment by JoelGodin** [comment]
He probably needs to know what version of Tissue are you using?

**Comment by alessandro-zomparelli** [comment]
Yes, it's better for me to know the version if Tissue. Also, I see that you are using an old version of Blender. Is there a particular reason? Otherwise I recommend using Tissue 0.3.39 with Blender 2.82a. Just tested and it works form me with this configuration.

**Comment by Carolin19** [comment]
Hello :) I got the same problem, Blender 2.81a and installed tissue-0-3-39. I would get this error
<img width="714" alt="Bildschirmfoto 2020-05-18 um 07 22 41" src="https://user-images.githubusercontent.com/50742053/82176911-5e429080-98d8-11ea-92e0-1ed5a626cdc4.png">
I also reinstalled and restarted Blender, already. 
Thank you. 
C

**Comment by alessandro-zomparelli** [comment]
Hi @Carolin19 you said Blender 2.81a? The latest version is 2.82a. For Tissue I fixed some bugs recently in this branch, maybe you can try that: https://github.com/alessandro-zomparelli/tissue/tree/b280-dev
Otherwise you can send me your file I can understand better what's the problem.

To me it seems that it's not finding the component that should have been created automatically:
![image](https://user-images.githubusercontent.com/6708848/82191180-70c9c380-98f2-11ea-9792-42e755fec56b.png)
Check in the outliner, the object by default is unselectable and hidden.
