### ISSUE TITLE
dual mesh in mesh tissue

### ISSUE THREAD

**Issue by profly50** [alessandro-zomparelli/tissue#70]
the dual mesh doesn't work well with triangles see image.

![DUAL MESH ISSUE](https://user-images.githubusercontent.com/66308318/83511359-d14e2880-a4ce-11ea-875a-f7ec7d28ac58.PNG)

**Comment by alessandro-zomparelli** [comment]
Hi @profly50 when you use "Dual-Mesh" it actually asks you if you are dealing with quads or triangles. If you have both, you could ad a triangulate modifier to your object and then use "Triangle" method.
Otherwise you can use the destructive method that is "Convert to Dual-Mesh", it should works fine with all kind of polygons.

**Comment by alessandro-zomparelli** [comment]
@profly50 no problem. I'll close the issue.
