### ISSUE TITLE
"Polyhedra Wireframe" gives weird result on some sort of geometry

### ISSUE THREAD

**Issue by portnov** [alessandro-zomparelli/tissue#91]
Given this sort of object:
![Screenshot_20201219_195424](https://user-images.githubusercontent.com/284644/102692269-0d12ca80-4234-11eb-8cda-ad38028e317a.png)
by applying "polyhedra wireframe" we will have weird spikes:
![Screenshot_20201219_195535](https://user-images.githubusercontent.com/284644/102692291-3c293c00-4234-11eb-870e-c92ca3497365.png)

Blend file attached:
[polyhedra_test_1.zip](https://github.com/alessandro-zomparelli/tissue/files/5719590/polyhedra_test_1.zip)

**Comment by alessandro-zomparelli** [comment]
Hi @portnov as I can see, your mesh is a Manifold surface, it means that there is no reason for a Polyhedra Wireframe, because for this type of geometry the regular Wireframe Modifier works fine. Actually, it gives you the possibility to disable the option "Even" that generate the "spike":
![image](https://user-images.githubusercontent.com/6708848/104111963-eb63ab00-52e8-11eb-8af1-e688f726e489.png)

Regarding the other thin edge, that's a common problem between the two methods. It's not actually a problem, it is more how it works. I had in mind to implement some more refined strategies for adding extra loops . I will do that, in the future.

**Comment by portnov** [comment]
No, this is not a manifold, since there is a face inside this separating two volumes of the mesh...

**Comment by alessandro-zomparelli** [comment]
![image](https://user-images.githubusercontent.com/6708848/104120566-145f5c80-5338-11eb-9713-1542fd17fb34.png)
I think it is... I also tried to Select Non-manifolds.
Anyway, with or without the inner face, if you reduce the thickness it should prevent the spike. You have very narrow angles that are not that compatible with the thickness that you are using...

**Comment by portnov** [comment]
Could the add-on just leave such "too narrow" faces as "walls"?

**Comment by alessandro-zomparelli** [comment]
That's a good point. It used to have that option. Then I had to rewrite it and this feature hasn't been updated yet... sorry :-(

**Comment by alessandro-zomparelli** [comment]
Hi @portnov such feature has been recently restored. You can find it here: 
![image](https://github.com/alessandro-zomparelli/tissue/assets/6708848/9074c91d-ef63-487a-b7ca-8438537e4493)
