### ISSUE TITLE
Render Gallery

### ISSUE THREAD

**Issue by onerawartist** [alessandro-zomparelli/tissue#92]
I thought everyone should share his work here sometime, as a '' thank you '' to alessandro zomparelli for this amazing addon. And maybe have a micro community, where people share knowledge and questions

**Comment by onerawartist** [comment]
![Concept 39.png](https://user-images.githubusercontent.com/71472224/102814945-d079d700-43cb-11eb-8348-7d2faf345b17.png)
![Concept 39 details.png](https://user-images.githubusercontent.com/71472224/102814983-e9828800-43cb-11eb-8b3a-9548592c1271.png)
I used the same mesh and two components one as quads and one as frame.
I hope its interesting for you guys
https://linktr.ee/one_raw_artist

**Comment by alessandro-zomparelli** [comment]
That's really nice! It's great to see people doing some advanced stuff :-) 

Long ago I asked the Blender Foundation to create a community for Architecture and Computational-Design on https://blender.community/ Unfortunately is taking longer because they are updating the whole community system.
Besides that, you can use the FaceBook group: https://www.facebook.com/groups/blendercomputationaldesign
Hashtag #blendertissue on the socialmedia (Twitter, Instagram, ...)

We can also use this thread, it's actually a nice idea! :-)
